# This workflow should verify code quality and build the project to test for errors.

name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '*.ts'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'

jobs:
  
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [ 16.x ]
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
      
  lint:
    name: Code Quality
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [ 16.x ]
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Dependencies
      run: npm ci
    - name: Code Quality
      run: npm run lint --if-present

